#!/bin/sh /etc/rc.common

START=96
STOP=04
USE_PROCD=1

PROG="/usr/libexec/vnt2/upload-worker"

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 0
	procd_set_param stderr 0
	procd_set_param term_timeout 5
	procd_close_instance
}
